### ISSUE TITLE
auth failed

### ISSUE THREAD

**Issue by Ravan1190** [AR-CADE/pluto_tv#1]
hey,

I also want to make app like pluto_tv how can i make ? I runned the pluto_tv in my pc its shows authentication failed not loading channels.

Edited: I also have many paid channels and i want to make like pluto_tv :(

how do i contact you ? do you have telegram id ?

**Comment by AR-CADE** [comment]
Hi,

> I also want to make app like pluto_tv how can i make ?

ha ha you just need to learn flutter :-)

> I runned the pluto_tv in my pc its shows authentication failed not loading channels.

can you describe how you ran to this issue step by step ?

i also need info like: 
- Your platform (linux, android, windows, web, etc..)
- Your flutter version
- The commit version that you currently use and that cause the problem
- Is there any previous commit version that worked for you ?

**NOTE**:
**it's not documented but if you want to test pluto_tv on web, you will need to disable CORS (you can use a plugin like this one : https://chrome.google.com/webstore/detail/cross-domain-cors/mjhpgnbimicffchbodmgfnemoghjakai)**
 

**on macos (an maybe ios too) you will need to enable internet permission as documented here: https://docs.flutter.dev/data-and-backend/networking#macos
just add:**
```
<key>com.apple.security.network.client</key>
<true/>
```
 **to `macos/Runner/DebugProfile.entitlements` and/or `macos/Runner/Release.entitlements` before compiling,
i will edit the repo if you can confirm that it works**

**On Linux, windows and macos, you can also use the electron version, that is in fact the recommended one as for now. 
Type:**
```
npm install
npm run build
```
**got to the `dist` directory to find the binary.**

> Edited: I also have many paid channels and i want to make like pluto_tv :(
> how do i contact you ? do you have telegram id ?

i don't have a telegram for now and since i live in france maybe never => https://adguard.com/en/blog/france-web-browser-dns-blocking-law.html, https://www.laquadrature.net/2023/09/12/projet-de-loi-sren-le-gouvernement-sourd-a-la-realite-dinternet/,

to be honest even my presence on github is compromised, but for now you can still contact me on my emails : **armelcadetpetit@gmail.com** or **arm-cade@proton.me**

just describe me your project i would be happy to help ... and then we could initialize a **private** chat if needed.

Peace out.

**Comment by Ravan1190** [comment]
>> can you describe how you ran to this issue step by step ?
>>
>> i also need info like:
>> 
>> * Your platform (linux, android, windows, web, etc..)
>> * Your flutter version
>> * The commit version that you currently use and that cause the problem
>> * Is there any previous commit version that worked for you ?

- Platform: I'm developing for the Android platform using IntelliJ IDEA.

- Flutter Version: I'm using the latest version of Flutter, which is 3.13.5.

- Commit Version: I encountered the issue right after cloning the repository. Unfortunately, I didn't note the specific commit version that caused the problem.

- Previous Working Version: Since I ran the repository for the first time yesterday without making any changes, there isn't a previous commit version that worked for me.


>> i don't have a telegram for now and since i live in france maybe never => https://adguard.com/en/blog/france-web-browser-dns-blocking-law.html, https://www.laquadrature.net/2023/09/12/projet-de-loi-sren-le-gouvernement-sourd-a-la-realite-dinternet/,
>> 
I understand your concerns about online privacy and the current internet regulations in France. It's important to prioritize your privacy and security when using online communication tools. Given your situation, we can continue our conversation via email, as you mentioned in your previous message.

>> just describe me your project i would be happy to help ... and then we could initialize a **private** chat if needed.

Thank you for considering collaborating with me, and I look forward to hearing from you via email.
